/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinnersRouteImport } from './routes/winners'
import { Route as RaffleRouteImport } from './routes/raffle'
import { Route as PublicRelationsRouteImport } from './routes/public-relations'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as EnterRouteImport } from './routes/enter'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BasketRouteImport } from './routes/basket'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RaffleIdRouteImport } from './routes/raffle.$id'
import { Route as MembersAllocateRouteImport } from './routes/members.allocate'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const WinnersRoute = WinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => rootRouteImport,
} as any)
const RaffleRoute = RaffleRouteImport.update({
  id: '/raffle',
  path: '/raffle',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRelationsRoute = PublicRelationsRouteImport.update({
  id: '/public-relations',
  path: '/public-relations',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterRoute = EnterRouteImport.update({
  id: '/enter',
  path: '/enter',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketRoute = BasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RaffleIdRoute = RaffleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RaffleRoute,
} as any)
const MembersAllocateRoute = MembersAllocateRouteImport.update({
  id: '/allocate',
  path: '/allocate',
  getParentRoute: () => MembersRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/basket': typeof BasketRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/enter': typeof EnterRoute
  '/faqs': typeof FaqsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/public-relations': typeof PublicRelationsRoute
  '/raffle': typeof RaffleRouteWithChildren
  '/winners': typeof WinnersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/members/allocate': typeof MembersAllocateRoute
  '/raffle/$id': typeof RaffleIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/basket': typeof BasketRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/enter': typeof EnterRoute
  '/faqs': typeof FaqsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/public-relations': typeof PublicRelationsRoute
  '/raffle': typeof RaffleRouteWithChildren
  '/winners': typeof WinnersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/members/allocate': typeof MembersAllocateRoute
  '/raffle/$id': typeof RaffleIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/basket': typeof BasketRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/enter': typeof EnterRoute
  '/faqs': typeof FaqsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/public-relations': typeof PublicRelationsRoute
  '/raffle': typeof RaffleRouteWithChildren
  '/winners': typeof WinnersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/members/allocate': typeof MembersAllocateRoute
  '/raffle/$id': typeof RaffleIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/basket'
    | '/community'
    | '/contact'
    | '/enter'
    | '/faqs'
    | '/login'
    | '/members'
    | '/public-relations'
    | '/raffle'
    | '/winners'
    | '/auth/callback'
    | '/checkout/return'
    | '/members/allocate'
    | '/raffle/$id'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/basket'
    | '/community'
    | '/contact'
    | '/enter'
    | '/faqs'
    | '/login'
    | '/members'
    | '/public-relations'
    | '/raffle'
    | '/winners'
    | '/auth/callback'
    | '/checkout/return'
    | '/members/allocate'
    | '/raffle/$id'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/basket'
    | '/community'
    | '/contact'
    | '/enter'
    | '/faqs'
    | '/login'
    | '/members'
    | '/public-relations'
    | '/raffle'
    | '/winners'
    | '/auth/callback'
    | '/checkout/return'
    | '/members/allocate'
    | '/raffle/$id'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  BasketRoute: typeof BasketRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  EnterRoute: typeof EnterRoute
  FaqsRoute: typeof FaqsRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRouteWithChildren
  PublicRelationsRoute: typeof PublicRelationsRoute
  RaffleRoute: typeof RaffleRouteWithChildren
  WinnersRoute: typeof WinnersRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/winners': {
      id: '/winners'
      path: '/winners'
      fullPath: '/winners'
      preLoaderRoute: typeof WinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raffle': {
      id: '/raffle'
      path: '/raffle'
      fullPath: '/raffle'
      preLoaderRoute: typeof RaffleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-relations': {
      id: '/public-relations'
      path: '/public-relations'
      fullPath: '/public-relations'
      preLoaderRoute: typeof PublicRelationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter': {
      id: '/enter'
      path: '/enter'
      fullPath: '/enter'
      preLoaderRoute: typeof EnterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket': {
      id: '/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof BasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raffle/$id': {
      id: '/raffle/$id'
      path: '/$id'
      fullPath: '/raffle/$id'
      preLoaderRoute: typeof RaffleIdRouteImport
      parentRoute: typeof RaffleRoute
    }
    '/members/allocate': {
      id: '/members/allocate'
      path: '/allocate'
      fullPath: '/members/allocate'
      preLoaderRoute: typeof MembersAllocateRouteImport
      parentRoute: typeof MembersRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MembersRouteChildren {
  MembersAllocateRoute: typeof MembersAllocateRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersAllocateRoute: MembersAllocateRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

interface RaffleRouteChildren {
  RaffleIdRoute: typeof RaffleIdRoute
}

const RaffleRouteChildren: RaffleRouteChildren = {
  RaffleIdRoute: RaffleIdRoute,
}

const RaffleRouteWithChildren =
  RaffleRoute._addFileChildren(RaffleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  BasketRoute: BasketRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  EnterRoute: EnterRoute,
  FaqsRoute: FaqsRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRouteWithChildren,
  PublicRelationsRoute: PublicRelationsRoute,
  RaffleRoute: RaffleRouteWithChildren,
  WinnersRoute: WinnersRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
